services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            dockerfile: docker/Dockerfile
            secrets:
              - auth_toml
        volumes:
            - ./:/src
        secrets:
          - source: auth_toml
            target: /home/app/.config/pypoetry/auth.toml
        ports:
            - 8506:8506
        depends_on:
            qualification_db:
              condition: service_healthy
        networks:
            - gfmodules-qualification

    qualification_db:
        image: postgres:14
        healthcheck:
          test: [ "CMD-SHELL", "pg_isready --user postgres"]
          start_period: 30s
          start_interval: 1s
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            -   5406:5432
        networks:
            - gfmodules-qualification

secrets:
  auth_toml:
    file: ./auth.toml

networks:
  gfmodules-qualification:
    driver: bridge
    name: gfmodules-qualification
