version: "3.5"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/src
        ports:
            - 8506:8506
        depends_on:
            - qualification_db
        networks:
            - gfmodules-qualification

    qualification_db:
        image: postgres:14
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            -   5406:5432
        networks:
            - gfmodules-qualification

networks:
  gfmodules-qualification:
    driver: bridge
    name: gfmodules-qualification
