version: "3.5"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./:/src
        ports:
            - 8506:8506
        networks:
            - gfmodules-qualification

    qualification_db:
        image: postgres:14
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            -   5406:5432
        networks:
            - gfmodules-qualification

    app-init:
        image: postgres:14
        depends_on: [ 'app', 'qualification_db' ]
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        working_dir: /src
        volumes:
            - ./:/src
        networks:
            - gfmodules-qualification
        command: bash -c 'sleep 2 && tools/./migrate_db.sh qualification_db postgres postgres postgres'

networks:
  gfmodules-qualification:
    driver: bridge
    name: gfmodules-qualification
